export const inputFormElements21 = [
    {
        name: "CompanyId",
        label: "CompanyId",
        variant: "outlined",
        fullWidth: true,
        required: true,
        xs: 12,
        sm: 6,
        
    },
    {
        name: "BranchId",
        label: "BranchId",
        variant: "outlined",
        fullWidth: true,
        required: true,
        xs: 12,
        sm: 6,
        
    },
{
    name: "ReferenceNo",
    label: "ReferenceNo", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "Employeeid",
    label: "Employeeid", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "JoiningDate",
    label: "JoiningDate", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "LastWorkingDate",
    label: "LastWorkingDate", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "ServiceYear",
    label: "ServiceYear", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
    type:"date"
},
{
    name: "GrauityAmount",
    label: "GrauityAmount", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "PfAmount",
    label: "PfAmount", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
    
},
{
    name: "EncashmentAmount",
    label: "EncashmentAmount", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "LoanAmount",
    label: "LoanAmount", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "DeductSalaryAmount",
    label: "DeductSalaryAmount", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "FinalAmount",
    label: "FinalAmount", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "Status",
    label: "Status", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},

]