export const inputFormElements19 = [
    // {
    //     name: "CompanyId",
    //     label: "CompanyId",
    //     variant: "outlined",
    //     fullWidth: true,
    //     required: true,
    //     xs: 12,
    //     sm: 6,
        
    // },
    // {
    //     name: "BranchId",
    //     label: "BranchId",
    //     variant: "outlined",
    //     fullWidth: true,
    //     required: true,
    //     xs: 12,
    //     sm: 6,
        
    // },
// {
//     name: "EmployeeId",
//     label: "EmployeeId", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm: 6,
// },
// {
//     name: "NomineeName",
//     label: "NomineeName", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm: 6,
// },
// {
//     name: "Gender",
//     label: "Gender", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm: 6,
// },
// {
//     name: "Dob",
//     label: "Dob", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm: 6,
//     type:"date"
// },
// {
//     name: "PfShare",
//     label: "PfShare", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm: 6,
// },
// {
//     name: "Relationship",
//     label: "Relationship", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm: 6,
// },
// {
//     name: "Address1",
//     label: "Address1", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm: 6,
// },
// {
//     name: "State",
//     label: "State", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm: 6,
    
// },
// {
//     name: "District",
//     label: "District", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm: 6,
// },
// {
//     name: "City",
//     label: "City", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm: 6,
// },
// {
//     name: "PinNo",
//     label: "PinNo", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm: 6,
// },



]