export const inputFormElements18 = [
    // {
    //     name: "pnCompanyId",
    //     label: "CompanyId",
    //     variant: "outlined",
    //     fullWidth: true,
    //     required: true,
    //     xs: 12,
    //     sm: 6,
        
    // },
    // {
    //     name: "pnBranchId",
    //     label: "BranchId",
    //     variant: "outlined",
    //     fullWidth: true,
    //     required: true,
    //     xs: 12,
    //     sm: 6,
        
    // },
// {
//     name: "machineNum",
//     label: "MachineNum", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm: 6,
// },
// {
//     name: "cardNo",
//     label: "CardNo", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm: 6,
// },
// {
//     name: "empCode",
//     label: "EmpCode", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm: 6,
// },
// {
//     name: "empName",
//     label: "EmpName", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm: 6,
// // },
// {
//     name: "verifyMode",
//     label: "VerifyMode", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm: 6,
// },
// {
//     name: "inOutMode",
//     label: "InOutMode", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm: 6,
// },
// {
//     name: "shiftCode",
//     label: "ShiftCode", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm: 6,
// },
// {
//     name: "dates",
//     label: "dates", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm: 6,
//     type:"datetime-local"
// },
// {
//     name: "days",
//     label: "Days", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm: 6,
// },
// {
//     name: "times",
//     label: "Times", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm: 6,
// },

// {
//     name: "status",
//     label: "Status", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm: 6,
// },


]