export const inputFormElements18 = [
    {
        name: "CompanyId",
        label: "CompanyId",
        variant: "outlined",
        fullWidth: true,
        required: true,
        xs: 12,
        sm: 6,
        
    },
    {
        name: "BranchId",
        label: "BranchId",
        variant: "outlined",
        fullWidth: true,
        required: true,
        xs: 12,
        sm: 6,
        
    },
{
    name: "MachineNum",
    label: "MachineNum", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "CardNo",
    label: "CardNo", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "EmpCode",
    label: "EmpCode", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "EmpName",
    label: "EmpName", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "VerifyMode",
    label: "VerifyMode", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "InOutMode",
    label: "InOutMode", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "ShiftCode",
    label: "ShiftCode", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "Dates",
    label: "Dates", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
    type:"datetime-local"
},
{
    name: "Days",
    label: "Days", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "Times",
    label: "Times", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "OtHrs",
    label: "OtHrs", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "Status",
    label: "Status", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},


]