export const inputFormElements22 = [
    {
        name: "CompanyId",
        label: "CompanyId",
        variant: "outlined",
        fullWidth: true,
        required: true,
        xs: 12,
        sm: 6,
        
    },
    {
        name: "EmployeeId",
        label: "EmployeeId",
        variant: "outlined",
        fullWidth: true,
        required: true,
        xs: 12,
        sm: 6,
        
    },
{
    name: "Loanid",
    label: "Loanid", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "Date",
    label: "Date", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
    type:"datetime-local"
},
{
    name: "DFromDate",
    label: "DFromDate", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
    type:"datetime-local"
},
{
    name: "DToDate",
    label: "DToDate", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
    type:"datetime-local"
},
{
    name: "Amount",
    label: "Amount", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "CountInstallement",
    label: "CountInstallement", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
    
},
{
    name: "Branchid",
    label: "Branchid", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "InstallementCount",
    label: "InstallementCount", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "LoanAppid",
    label: "LoanAppid", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "InstalAmt",
    label: "InstalAmt", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "BalanceAmt",
    label: "BalanceAmt", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "LoanStatus",
    label: "LoanStatus", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},

]