export const inputFormElements8 = [
    {
        name: "CompanyId",
        label: "CompanyId",
        variant: "outlined",
        fullWidth: true,
        required: true,
        xs: 12,
        sm: 6,
        
    },
{
    name: "BranchId",
    label: "BranchId", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "EmployeeCode",
    label: "EmployeeCode", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "EmployeeName",
    label: "EmployeeName", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "FromDate",
    label: "FromDate", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    type:"datetime-local"
},
{
    name: "ToDate",
    label: "ToDate", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    type:"datetime-local"
},
{
    name: "M1",
    label: "M1", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M2",
    label: "M2", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M3",
    label: "M3", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M4",
    label: "M4", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M5",
    label: "M5", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M6",
    label: "M6", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M7",
    label: "M7", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M8",
    label: "M8", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M9",
    label: "M9", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M10",
    label: "M10", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M11",
    label: "M11", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M12",
    label: "M12", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M13",
    label: "M13", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M14",
    label: "M14", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M15",
    label: "M15", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M16",
    label: "M16", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M17",
    label: "M17", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M18",
    label: "M18", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M19",
    label: "M19", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M20",
    label: "M20", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M21",
    label: "M21", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M22",
    label: "M22", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M23",
    label: "M23", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M24",
    label: "M24", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M25",
    label: "M25", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M26",
    label: "M26", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M27",
    label: "M27", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M28",
    label: "M28", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M29",
    label: "M29", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M30",
    label: "M30", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "M31",
    label: "M31", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "PrsDays",
    label: "PrsDays", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "LeaveDays",
    label: "LeaveDays", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "OdDays",
    label: "OdDays", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "Holidays",
    label: "Holidays", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "WeekOff",
    label: "WeekOff", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "AbsDays",
    label: "AbsDays", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "PaidDays",
    label: "PaidDays", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "GradeId",
    label: "GradeId", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
}, 


]