export const inputFormElements5 = [
    {
        name: "CompanyId",
        label: "CompanyId",
        variant: "outlined",
        fullWidth: true,
        required: true,
        xs: 12,
        sm: 6,
        select:true,
        options: [
            {value:"1", label:"Company 1"}, 
            {value:"2", label:"Company 2"}, 
        ]

    },
{
    name: "BranchId",
    label: "BranchId", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    select:true,
    options: [
        {value:"1", label:"Branch 1"}, 
        {value:"2", label:"Branch 2"}, 
    ]
   
},
{
    name: "Branch Code",
    label: "BranchId", 
    variant: "outlined", 
    label: "Branch Code",
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "Employee Code",
    label: "BranchId", 
    variant: "outlined", 
    label: "Employee Code",
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "Employee Name",
    label: "BranchId", 
    variant: "outlined", 
    label: "Employee Name",
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "Shift Code",
    label: "BranchId", 
    variant: "outlined", 
    label: "Shift Code",
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "Date",
    label: "BranchId", 
    variant: "outlined", 
    label: "Date",
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    type:"datetime-local"
},
{
    name: "Days",
    label: "BranchId", 
    variant: "outlined", 
    label: "Date",
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "In-Time",
    label: "BranchId", 
    variant: "outlined", 
    label: "In-Time",
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    type:"time"
},
{
    name: "Break-Out",
    label: "BranchId", 
    variant: "outlined", 
    label: "Break-Out",
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    type:"time"
},
{
    name: "Break-In",
    label: "BranchId", 
    variant: "outlined", 
    label: "Break-In",
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    type:"time"
},
{
    name: "Out-Time",
    label: "BranchId", 
    variant: "outlined", 
    label: "Out-Time",
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    type:"time"
},
{
    name: "Late-In",
    label: "BranchId", 
    variant: "outlined", 
    label: "Late-In",
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    type:"time"
},
{
    name: "Late-Out",
    label: "BranchId", 
    variant: "outlined", 
    label: "Late-Out",
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    type:"time"
},
{
    name: "Early-Out",
    label: "BranchId", 
    variant: "outlined", 
    label: "Early-Out",
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    type:"time"
},
{
    name: "Overtime Hrs",
    label: "BranchId", 
    variant: "outlined", 
    label: "Overtime Hrs",
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    type:"datetime-local"
},
{
    name: "Leave Code",
    label: "BranchId", 
    variant: "outlined", 
    label: "Leave Code",
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "Status",
    label: "BranchId", 
    variant: "outlined", 
    label: "Status",
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},

]