export const inputFormElements10 = [
    {
        name: "CompanyId",
        label: "CompanyId",
        variant: "outlined",
        fullWidth: true,
        required: true,
        xs: 12,
        sm: 6,
        
    },
{
    name: "EmployeeId",
    label: "EmployeeId", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "EarningsId",
    label: "EarningsId", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "DepartmentName",
    label: "DepartmentName", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "DDate",
    label: "DDate", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    type:"datetime-local"
},
{
    name: "DFromDate",
    label: "DFromDate", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    type:"datetime-local"
},
{
    name: "DToDate",
    label: "DToDate", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    type:"datetime-local"
},
{
    name: "Mode",
    label: "Mode", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "Flag",
    label: "Flag", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "ActAmount",
    label: "ActAmount", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "Amount",
    label: "Amount" , 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "BranchId",
    label: "BranchId", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "VEarningsname",
    label: "VEarningsname", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},



]