export const inputFormElements7 = [
    {
        name: "CompanyId",
        label: "CompanyId",
        variant: "outlined",
        fullWidth: true,
        required: true,
        xs: 12,
        sm: 6,
        
    },
{
    name: "BranchId",
    label: "BranchId", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "EmployeeId",
    label: "EmployeeId", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "DDate",
    label: "DDate", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    type:"datetime-local"
},
{
    name: "DFromDate",
    label: "DFromDate", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    type:"datetime-local"
},
{
    name: "DToDate",
    label: "DToDate", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    type:"datetime-local"
},
{
    name: "EarnActAmount",
    label: "EarnActAmount", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "EarnAmount",
    label: "EarnAmount", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,

},
{
    name: "OtAmt",
    label: "OtAmt", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "DedActAmount",
    label: "DedActAmount", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "DedAmount",
    label: "DedAmount", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,

},
{
    name: "NetPay",
    label: "NetPay", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,

},
{
    name: "ActBasic",
    label: "ActBasic", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "EarnedBasic",
    label: "EarnedBasic", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "GrossSalary",
    label: "GrossSalary", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "NetSalary",
    label: "NetSalary", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "PeriodCode",
    label: "PeriodCode", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "Epf",
    label: "Epf", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "Fpf",
    label: "Fpf", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},


]