export const inputFormElements6 = [
    {
        name: "CompanyId",
        label: "CompanyId",
        variant: "outlined",
        fullWidth: true,
        required: true,
        xs: 12,
        sm: 6,
        
    },
{
    name: "BranchId",
    label: "BranchId", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "EmployeeId",
    label: "EmployeeId", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "DDate",
    label: "DDate", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    type:"datetime-local"
},
{
    name: "DFromDate",
    label: "DFromDate", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    type:"datetime-local"
},
{
    name: "DToDate",
    label: "DToDate", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    type:"datetime-local"
},
{
    name: "CalcDays",
    label: "CalcDays", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    
},
{
    name: "PaidDays",
    label: "PaidDays", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    
},
{
    name: "PresentDays",
    label: "PresentDays", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "AbsentDays",
    label: "AbsentDays", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,

},
{
    name: "TotLeaveDays",
    label: "TotLeaveDays", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
   
},
{
    name: "WeekOffDays",
    label: "WeekOffDays", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    type:"datetime-local"
},
{
    name: "Hollidays",
    label: "Hollidays", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    
},
{
    name: "OnDutyDays",
    label: "OnDutyDays", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "CompoffDays",
    label: "CompoffDays", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "TourDays",
    label: "TourDays", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "AttBonus",
    label: "AttBonus", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "AttBonusAmount",
    label: "AttBonusAmount", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,

},
{
    name: "OtHrs ",
    label: "OtHrs ", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    type:"time"
},
{
    name: "EarnArrears",
    label: "EarnArrears", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
    
},
{
    name: "DedArrears",
    label: "DedArrears", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "OtValue",
    label: "OtValue", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,

},
{
    name: "OtAmt",
    label: "OtAmt", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "ActBasic",
    label: "ActBasic", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "EarnBasic",
    label: "EarnBasic", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "Mode",
    label: "Mode", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "Flag",
    label: "Flag", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "PtGross",
    label: "PtGross", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},
{
    name: "MaxAmount",
    label: "MaxAmount", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm:6,
},

]