export const inputFormElements24 = [
    {
        name: "CompanyId",
        label: "CompanyId",
        variant: "outlined",
        fullWidth: true,
        required: true,
        xs: 12,
        sm: 6,
        select:true,
        options: [
            {value:"1", label:"company 1"}, 
            {value:"2", label:"company 2"}, 
        ]
    },
    {
        name: "BranchId",
        label: "BranchId",
        variant: "outlined",
        fullWidth: true,
        required: true,
        xs: 12,
        sm: 6,
        select:true,
        options: [
            {value:"1", label:"company 1"}, 
            {value:"2", label:"company 2"}, 
        ]
        
    },
    {
        name: "EmpConPf",
        label: "EmpConPf",
        variant: "outlined",
        fullWidth: true,
        required: true,
        xs: 12,
        sm: 6,
        
    },
{
    name: "EmpConEpf",
    label: "EmpConEpf", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "EmpConFpf",
    label: "EmpConFpf", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "AdminCharges",
    label: "AdminCharges", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,

},
{
    name: "EligibilityAmt",
    label: "EligibilityAmt", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "CRound",
    label: "CRound", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "DDate",
    label: "DDate", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
    type:"datetime-local"
},
{
    name: "CheckCeiling",
    label: "CheckCeiling", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "MaxAmount",
    label: "MaxAmount", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "Month",
    label: "Month", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},
{
    name: "Year",
    label: "Year", 
    variant: "outlined", 
    fullWidth: true,
    required: true,
    xs:12, 
    sm: 6,
},

]