export const inputFormElements12 = [
//     {
//         name: "CompanyId",
//         label: "CompanyId",
//         variant: "outlined",
//         fullWidth: true,
//         required: true,
//         xs: 12,
//         sm: 12,
        
//     },
// {
//     name: "EmployeeId",
//     label: "EmployeeId", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm:12,
// },
// {
//     name: "PatternCode",
//     label: "PatternCode", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm:12,
// },
// {
//     name: "ShiftCode1",
//     label: "ShiftCode1", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm:6,
// },
// {
//     name: "Days1",
//     label: "Days1", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm:6,
// },
// {
//     name: "ShiftCode2",
//     label: "ShiftCode2", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm:6,
// },
// {
//     name: "Days2",
//     label: "Days2", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm:6,
// },
// {
//     name: "ShiftCode3",
//     label: "ShiftCode3", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm:6,
// },
// {
//     name: "Days3",
//     label: "Days3", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm:6,
// },
// {
//     name: "ShiftCode4",
//     label: "ShiftCode4", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm:6,
// },
// {
//     name: "Days4",
//     label: "Days4", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm:6,
// },
// {
//     name: "ShiftCode5",
//     label: "ShiftCode5", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm:6,
// },
// {
//     name: "Days5",
//     label: "Days5", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm:6,
// },
// {
//     name: "ShiftCode6",
//     label: "ShiftCode6", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm:6,
// },
// {
//     name: "Days6",
//     label: "Days6", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm:6,
// },
// {
//     name: "ShiftCode7",
//     label: "ShiftCode7", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm:6,
// },
// {
//     name: "Days7",
//     label: "Days7", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm:6,
// },
// {
//     name: "ShiftCode8",
//     label: "ShiftCode8", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm:6,
// },
// {
//     name: "Days8",
//     label: "Days8", 
//     variant: "outlined", 
//     fullWidth: true,
//     required: true,
//     xs:12, 
//     sm:6,
// },



]